### ISSUE TITLE
不知道是什么原因产生的问题

### ISSUE THREAD

**Issue by RtYkk** [shuangluoxss/Stage1st-downloader#2]
[腐女圈大事件](https://bbs.saraba1st.com/2b/thread-1916310-1-1.html)
这个帖子前前后后标题改了三次，所以根目录索引也有三个……
![explorer_O6yure065t](https://user-images.githubusercontent.com/45971730/75638689-211b1a80-5c68-11ea-8c5f-42cbca8a6a41.png)
但是很奇怪，我三个点进去全都是只能查看19页，19页之后的都看不到
![firefox_4KKaMrj5r6](https://user-images.githubusercontent.com/45971730/75638753-7525ff00-5c68-11ea-982c-f80636e694c5.png)

**Comment by shuangluoxss** [comment]
出现这种问题最大的可能是你第一次下载时帖子只有19页，之后下载时因为前19页已经下载所以没有更新，直接从20页开始下载的。
data文件夹中应该有thread-1916310-20-1.html及之后的页面，可以在跳页窗口手动输入19之后的页码尝试跳转。
写这个脚本时主要是想备份长期存在的专楼，没有考虑实时更新的问题。一种可行的解决方法是删除data文件夹中所有thread-1916310-*-1.html文件，重新下载即可覆盖。或者修改源代码，将downloader.py中122行处的
`download_page(self, filename, soup=None, force_refresh=False)`
修改为
`download_page(self, filename, soup=None, force_refresh=True)`
即可
